[package]
name = "EvOS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nostd_async = "0.6.1"
tinyrand = "0.5.0"

[[bin]]
name = "hello"
path = "src/hello.rs"